### PR TITLE
baselibs.conf: targetname is a valid keyword

### PR DESCRIPTION
**Pull request by DimStar77**

### CODE REVIEW

**Comment by DimStar77** [comment]
PING!

**Comment by coolo** [comment]
you need to tell rudi directly I guess

**Comment by bgeuken** [comment]
You mean @bugfinder ?;-)

**Comment by coolo** [comment]
yes, but when I say "tell directly" I meant other ways than github comments

**Comment by bugfinder** [comment]
looks good to me

**Pull request merged**
