### PR TITLE
added checker for filenames

### PR DESCRIPTION
**Pull request by M0ses**
@bugfinder @msmeissn Please review

### CODE REVIEW

**Comment by msmeissn** [comment]
also filter $ , and leading - to avoid option injection (- in the middle are ok).

**Comment by marcus-h** [comment]
Hmm it is still possible to fool around with escape sequences via a
dsc file. For example,

marcus@linux:~/obs-service-source_validator/c> cat osc.dsc 
Files:
 1 2 -e \\033]11;green\\007
marcus@linux:~/obs-service-source_validator/c>

changes the background color of your terminal to green (works at least
with urxvt).
The attached patch fixes this (it also adds a check for ".*" files and
some quotes (not necessarily needed, but better safe than sorry:) )).

**Comment by marcus-h** [comment]
[escape_sequences.diff.txt](https://github.com/openSUSE/obs-service-source_validator/files/242827/escape_sequences.diff.txt)
*sigh*... github neither supports a mail attachment nor a file with the *.diff extension...
(let's see if the manual upload worked:) ).

**Comment by M0ses** [comment]
@msmeissn @marcus-h 

THX for hints and contributions.

**Comment by M0ses** [comment]
@msmeissn : would this be an acceptable solution for the open bnc# ?

**Comment by msmeissn** [comment]
I did some tests, and while ` and single ' are not filtered, they do not seem to trigger bad behaviour anymore.  Perhaps still filter ` , but otherwise it is good.

**Comment by bugfinder** [comment]
looks good to me

**Pull request merged**
