### PR TITLE
Support multibuild checking

### PR DESCRIPTION
**Pull request by adrianschroeter**

### CODE REVIEW

**Comment by adrianschroeter** [comment]
@M0ses @marcus-h  this is basically preapare_spec function .... I am not sure why we had it exactly, my hope is that the multiple runs for each flavor achieves the same result, but I am not sure....

**Comment by adrianschroeter** [comment]
This solves the issue that multiple Name: definitions overwrite each other and leads to validation errors, for example in glibc case.

However, we don't evaluate all %if %else cases anymore. Eg. %ifarch or %if which calls script code.
Rudi sees a regression here...

**Comment by bugfinder** [comment]
I'm absolutely unsure here. We did the %if parsing for a reason. What we tried was to make all branches of an if/else/endif into if_true/endif if_true/endif to have all cases as true and thus get all possible variants of the definitions as we have no way of telling which way some macros may be set that the if's try to evaluate.

**Comment by adrianschroeter** [comment]
On Dienstag, 30. Januar 2018, 16:24:44 CET wrote Ruediger Oertel:
> I'm absolutely unsure here. We did the %if parsing for a reason. What we tried was to make all branches of an if/else/endif into if_true/endif if_true/endif to have all cases as true and thus get all possible variants of the definitions as we have no way of telling which way some macros may be set that the if's try to evaluate.

I understand this, but when you do the if _and_ the else case you overwrite variables or create 
situations which will never happen in real life (for example one thing XOR the other thing is 
set). 

In this particular case the second Name: tag always overwrites the first one.

-- 

Adrian Schroeter
email: adrian@suse.de

SUSE Linux GmbH, GF: Felix Imendörffer, Jane Smithard, Graham Norton, HRB 21284 (AG Nürnberg) 
 
Maxfeldstraße 5                         
90409 Nürnberg 
Germany

**Comment by mlschroe** [comment]
Hey, <package> is the obsolete syntax in a _multibuild file, you're supposed to use <flavor> nowadays! Please fix!

**Comment by adrianschroeter** [comment]
@mlschroe which obsolete syntax? The glibc example is following exactly our official schema files...

**Comment by adrianschroeter** [comment]
ah, `<flavor> `... we need to adapt this at many places ....

**Comment by mlschroe** [comment]
In that case the "official schema files" are outdated.

**Comment by adrianschroeter** [comment]
we could extend the validator to point out to the new syntax as well ... I doubt that anyone has used the new so far ...

**Comment by adrianschroeter** [comment]
updated to support also the new syntax.

**Comment by adrianschroeter** [comment]
okay, keep the old behaviour and disable the removal of conditions only for baselibs check for now.

**Comment by marcus-h** [comment]
On 2018-01-31 01:40:44 -0800, Michael Schroeder wrote:
> @mlschroe requested your review on: openSUSE/obs-service-source_validator#69 Support multibuild checking.
> 
I'm quite busy until sunday... so if it is really urgent
just merge it (but I might complain afterwards;) ). If not,
I'll have a look at it next monday/week.

**Comment by adrianschroeter** [comment]
okay, merging for now to get the glibc submission moving ...

**Comment by marcus-h** [comment]
On 2018-01-30 07:07:51 -0800, Adrian Schröter wrote:
> diff --git a/70-baselibs b/70-baselibs
> index f36f216..e97768b 100755
> --- a/70-baselibs
> +++ b/70-baselibs
> @@ -19,11 +19,19 @@ containsElement () {
>  [ -f $DIR_TO_CHECK/baselibs.conf ] || exit 0
>  
>  BUILTBINARIES=()
> -for i in "$DIR_TO_CHECK"/*.spec; do
> +if [ -e "$DIR_TO_CHECK/_multibuild" ]; then
> +  sed -n -e 's,.*<\(flavor\|package\)>\([^<]*\)</\(flavor\|package\)>.*,\2,p' \

Hmm maybe add the "g" option as well to support multiple elements on
the same line like "<flavor>foo</flavor><flavor>bar</flavor>".

> +    "$DIR_TO_CHECK/_multibuild" | while read i; do
>         # PASS if we have trouble parsing the .spec file
> -       BUILTBINARIES+=($($HELPERS_DIR/spec_query --specfile "$i" --print-subpacks \
> -           --no-conditionals)) || exit 0
> +       BUILTBINARIES+=($($HELPERS_DIR/spec_query --specfile "$DIR_TO_CHECK"/*.spec --print-subpacks \

This will fail in case of multiple *.spec files (not sure if this
make much sense in the multibuild case, though) - we could simply
move the multibuild stuff to the for loop below.

> +           --buildflavor $i)) || exit 0
> +  done
> +fi
> +for i in "$DIR_TO_CHECK"/*.spec; do
> +      # PASS if we have trouble parsing the .spec file
> +      BUILTBINARIES+=($($HELPERS_DIR/spec_query --specfile "$i" --print-subpacks)) || exit 0
>  done
>

**Comment by adrianschroeter** [comment]
On Dienstag, 6. Februar 2018, 12:56:09 CET wrote Marcus Hüwe:
> On 2018-01-30 07:07:51 -0800, Adrian Schröter wrote:
> > diff --git a/70-baselibs b/70-baselibs
> > index f36f216..e97768b 100755
> > --- a/70-baselibs
> > +++ b/70-baselibs
> > @@ -19,11 +19,19 @@ containsElement () {
> >  [ -f $DIR_TO_CHECK/baselibs.conf ] || exit 0
> >  
> >  BUILTBINARIES=()
> > -for i in "$DIR_TO_CHECK"/*.spec; do
> > +if [ -e "$DIR_TO_CHECK/_multibuild" ]; then
> > +  sed -n -e 's,.*<\(flavor\|package\)>\([^<]*\)</\(flavor\|package\)>.*,\2,p' \
> 
> Hmm maybe add the "g" option as well to support multiple elements on
> the same line like "<flavor>foo</flavor><flavor>bar</flavor>".

can't hurd ... a real parser would be better anyway...

> > +    "$DIR_TO_CHECK/_multibuild" | while read i; do
> >         # PASS if we have trouble parsing the .spec file
> > -       BUILTBINARIES+=($($HELPERS_DIR/spec_query --specfile "$i" --print-subpacks \
> > -           --no-conditionals)) || exit 0
> > +       BUILTBINARIES+=($($HELPERS_DIR/spec_query --specfile "$DIR_TO_CHECK"/*.spec --print-subpacks \
> 
> This will fail in case of multiple *.spec files (not sure if this
> make much sense in the multibuild case, though) - we could simply
> move the multibuild stuff to the for loop below.

right, there should have been another loop ... where did it go.

both changed in git master now

-- 

Adrian Schroeter
email: adrian@suse.de

SUSE Linux GmbH, GF: Felix Imendörffer, Jane Smithard, Graham Norton, HRB 21284 (AG Nürnberg) 
 
Maxfeldstraße 5                         
90409 Nürnberg 
Germany

**Pull request merged**
